### ISSUE TITLE
Explanation of the dataset

### ISSUE THREAD

**Issue by bened1ktz1pfel** [Jesmine0902/Machine-Scheduling-with-2D-packing-in-AM#1]
Hey there,
could you give me a short explanation of the data set?
I could find out some of them, but not all. Thanks in advance. :)

Benedikt

**Comment by Jesmine0902** [comment]
> Hey there,
> could you give me a short explanation of the data set?
> I could find out some of them, but not all. Thanks in advance. :)
> 
> Benedikt

Hi Benedikt,

Thanks for your interest in this topic.

The dataset is an original version used for experiments, and we updated the dataset already. You are recommended to read our paper for information via the links (https://authors.elsevier.com/a/1cf-u_6xwSR9r5). The link to the dataset is attached in the paper ( section 7. Experiments and analysis ), and you can also find an explanation of the data set there.

For reference :
Yuxin Che, Kanxin Hun, Zhenzhen Zhang, and Andrew Lim. "Machine scheduling with orientation selection and two-dimensional packing for additive manufacturing." Computers & Operations Research (2021): 105245.

Regards,
Yuxin

**Comment by bened1ktz1pfel** [comment]
Hi Yuxin,

thank you so much for the quick response to my question.

That is exactly what I was looking for. Once again, thank you so much! I somehow oversaw the reference-link in your paper and searched for the data set you used here on GitHub.

Regards,
Benedikt
